notARepository: skip

gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - default
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
    cherryPickedCommitBgColor:
      - black
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
    searchingActiveBorderColor:
      - yellow
