"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 500

format = """
$directory\
$python\
$character\
"""

right_format = """
$git_branch\
"""

[directory]
format = "$path "
truncation_length = 3
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[➜](bold cyan)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[➜](bold cyan)"
vimcmd_visual_symbol = "[➜](bold cyan)"
vimcmd_replace_symbol = "[➜](bold cyan)"
vimcmd_replace_one_symbol = "[➜](bold cyan)"

[python]
symbol = ""
format = "[\\($virtualenv\\)]($style) "
style = "dimmed"
detect_extensions = []
detect_files = []
detect_folders = []

[cmd_duration]
min_time = 2000
format = "[󰔛 $duration](bright-black) "
show_milliseconds = false

[git_branch]
symbol = " "
style = "fg:bright-magenta bg:black"
format = "[](fg:black)[$symbol$branch]($style)[](fg:black)"
truncation_length = 24
truncation_symbol = "…"
