set -g @thm_bg "{background}"
set -g @thm_fg "{foreground}"

set -g @thm_rosewater "{foreground}"
set -g @thm_flamingo "{color7}"
set -g @thm_pink "{color13}"
set -g @thm_mauve "{color5}"
set -g @thm_red "{color1}"
set -g @thm_maroon "{color9}"
set -g @thm_peach "{color3}"
set -g @thm_yellow "{color11}"
set -g @thm_green "{color2}"
set -g @thm_teal "{color6}"
set -g @thm_sky "{color14}"
set -g @thm_sapphire "{color6}"
set -g @thm_blue "{color4}"
set -g @thm_lavender "{color12}"

set -g @thm_subtext_1 "{color7}"
set -g @thm_subtext_0 "{foreground}"
set -g @thm_overlay_2 "{color8}"
set -g @thm_overlay_1 "{color8}"
set -g @thm_overlay_0 "{color8}"
set -g @thm_surface_2 "{color8}"
set -g @thm_surface_1 "{color0}"
set -g @thm_surface_0 "{color0}"
set -g @thm_mantle "{color0}"
set -g @thm_crust "{background}"
